//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.PropertyEditing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.PropertyEditing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string AlphaInitial {
            get {
                return ResourceManager.GetString("AlphaInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string BlackInitial {
            get {
                return ResourceManager.GetString("BlackInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BlueInitial {
            get {
                return ResourceManager.GetString("BlueInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BrightnessInitial {
            get {
                return ResourceManager.GetString("BrightnessInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMYK.
        /// </summary>
        public static string CMYK {
            get {
                return ResourceManager.GetString("CMYK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string ColorEditorTabLabel {
            get {
                return ResourceManager.GetString("ColorEditorTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color space.
        /// </summary>
        public static string ColorSpace {
            get {
                return ResourceManager.GetString("ColorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Local Value.
        /// </summary>
        public static string ConvertToLocalValue {
            get {
                return ResourceManager.GetString("ConvertToLocalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current color.
        /// </summary>
        public static string CurrentColor {
            get {
                return ResourceManager.GetString("CurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom expression.
        /// </summary>
        public static string CustomExpression {
            get {
                return ResourceManager.GetString("CustomExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Expression….
        /// </summary>
        public static string CustomExpressionEllipsis {
            get {
                return ResourceManager.GetString("CustomExpressionEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string CyanInitial {
            get {
                return ResourceManager.GetString("CyanInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan / Magenta / Yellow / Black.
        /// </summary>
        public static string CyanMagentaYellowBlack {
            get {
                return ResourceManager.GetString("CyanMagentaYellowBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handlers for the selected element.
        /// </summary>
        public static string EventHandlersSelectedElement {
            get {
                return ResourceManager.GetString("EventHandlersSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string GreenInitial {
            get {
                return ResourceManager.GetString("GreenInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex value.
        /// </summary>
        public static string HexValue {
            get {
                return ResourceManager.GetString("HexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLS.
        /// </summary>
        public static string HLS {
            get {
                return ResourceManager.GetString("HLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSB.
        /// </summary>
        public static string HSB {
            get {
                return ResourceManager.GetString("HSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string HueInitial {
            get {
                return ResourceManager.GetString("HueInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue / Lightness / Saturation.
        /// </summary>
        public static string HueLightnessSaturation {
            get {
                return ResourceManager.GetString("HueLightnessSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue / Saturation / Brightness.
        /// </summary>
        public static string HueSaturationBrightness {
            get {
                return ResourceManager.GetString("HueSaturationBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        public static string Inherited {
            get {
                return ResourceManager.GetString("Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial color.
        /// </summary>
        public static string InitialColor {
            get {
                return ResourceManager.GetString("InitialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an Invalid Value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last color.
        /// </summary>
        public static string LastColor {
            get {
                return ResourceManager.GetString("LastColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness.
        /// </summary>
        public static string Lightness {
            get {
                return ResourceManager.GetString("Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string LightnessInitial {
            get {
                return ResourceManager.GetString("LightnessInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MagentaInitial {
            get {
                return ResourceManager.GetString("MagentaInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string MaterialColorAmber {
            get {
                return ResourceManager.GetString("MaterialColorAmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and White.
        /// </summary>
        public static string MaterialColorBlackAndWhite {
            get {
                return ResourceManager.GetString("MaterialColorBlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string MaterialColorBlue {
            get {
                return ResourceManager.GetString("MaterialColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Grey.
        /// </summary>
        public static string MaterialColorBlueGrey {
            get {
                return ResourceManager.GetString("MaterialColorBlueGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string MaterialColorBrown {
            get {
                return ResourceManager.GetString("MaterialColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string MaterialColorCyan {
            get {
                return ResourceManager.GetString("MaterialColorCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Orange.
        /// </summary>
        public static string MaterialColorDeepOrange {
            get {
                return ResourceManager.GetString("MaterialColorDeepOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Purple.
        /// </summary>
        public static string MaterialColorDeepPurple {
            get {
                return ResourceManager.GetString("MaterialColorDeepPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string MaterialColorGreen {
            get {
                return ResourceManager.GetString("MaterialColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string MaterialColorGrey {
            get {
                return ResourceManager.GetString("MaterialColorGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string MaterialColorIndigo {
            get {
                return ResourceManager.GetString("MaterialColorIndigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        public static string MaterialColorLightBlue {
            get {
                return ResourceManager.GetString("MaterialColorLightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        public static string MaterialColorLightGreen {
            get {
                return ResourceManager.GetString("MaterialColorLightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        public static string MaterialColorLime {
            get {
                return ResourceManager.GetString("MaterialColorLime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string MaterialColorOrange {
            get {
                return ResourceManager.GetString("MaterialColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string MaterialColorPink {
            get {
                return ResourceManager.GetString("MaterialColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string MaterialColorPurple {
            get {
                return ResourceManager.GetString("MaterialColorPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string MaterialColorRed {
            get {
                return ResourceManager.GetString("MaterialColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string MaterialColorTeal {
            get {
                return ResourceManager.GetString("MaterialColorTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string MaterialColorYellow {
            get {
                return ResourceManager.GetString("MaterialColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Design Colors.
        /// </summary>
        public static string MaterialDesignColorBrush {
            get {
                return ResourceManager.GetString("MaterialDesignColorBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects selected.
        /// </summary>
        public static string MultipleObjectsSelected {
            get {
                return ResourceManager.GetString("MultipleObjectsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} types selected.
        /// </summary>
        public static string MultipleTypesSelected {
            get {
                return ResourceManager.GetString("MultipleTypesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No brush.
        /// </summary>
        public static string NoBrush {
            get {
                return ResourceManager.GetString("NoBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Name&gt;.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties for the selected element.
        /// </summary>
        public static string PropertiesSelectedElement {
            get {
                return ResourceManager.GetString("PropertiesSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red / Green/ Blue.
        /// </summary>
        public static string RedGreenBlue {
            get {
                return ResourceManager.GetString("RedGreenBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string RedInitial {
            get {
                return ResourceManager.GetString("RedInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush from resource.
        /// </summary>
        public static string ResourceBrush {
            get {
                return ResourceManager.GetString("ResourceBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource….
        /// </summary>
        public static string ResourceEllipsis {
            get {
                return ResourceManager.GetString("ResourceEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SaturationInitial {
            get {
                return ResourceManager.GetString("SaturationInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Objects.
        /// </summary>
        public static string SearchObjectsTitle {
            get {
                return ResourceManager.GetString("SearchObjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search properties.
        /// </summary>
        public static string SearchProperties {
            get {
                return ResourceManager.GetString("SearchProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Resources.
        /// </summary>
        public static string SearchResourcesTitle {
            get {
                return ResourceManager.GetString("SearchResourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Object.
        /// </summary>
        public static string SelectObjectTitle {
            get {
                return ResourceManager.GetString("SelectObjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Resource.
        /// </summary>
        public static string SelectResourceTitle {
            get {
                return ResourceManager.GetString("SelectResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show advanced properties.
        /// </summary>
        public static string ShowAdvancedProperties {
            get {
                return ResourceManager.GetString("ShowAdvancedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show all assemblies.
        /// </summary>
        public static string ShowAllAssemblies {
            get {
                return ResourceManager.GetString("ShowAllAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show system resources.
        /// </summary>
        public static string ShowSystemResources {
            get {
                return ResourceManager.GetString("ShowSystemResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid color brush.
        /// </summary>
        public static string SolidBrush {
            get {
                return ResourceManager.GetString("SolidBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View properties or events.
        /// </summary>
        public static string ViewPropertiesOrEvents {
            get {
                return ResourceManager.GetString("ViewPropertiesOrEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string YellowInitial {
            get {
                return ResourceManager.GetString("YellowInitial", resourceCulture);
            }
        }
    }
}
