//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.PropertyEditing.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.PropertyEditing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        public static string AlphaInitial {
            get {
                return ResourceManager.GetString("AlphaInitial", resourceCulture);
            }
        }
        
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        public static string BlackInitial {
            get {
                return ResourceManager.GetString("BlackInitial", resourceCulture);
            }
        }
        
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        public static string BlueInitial {
            get {
                return ResourceManager.GetString("BlueInitial", resourceCulture);
            }
        }
        
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        public static string BrightnessInitial {
            get {
                return ResourceManager.GetString("BrightnessInitial", resourceCulture);
            }
        }
        
        public static string CMYK {
            get {
                return ResourceManager.GetString("CMYK", resourceCulture);
            }
        }
        
        public static string ColorSpace {
            get {
                return ResourceManager.GetString("ColorSpace", resourceCulture);
            }
        }
        
        public static string CurrentColor {
            get {
                return ResourceManager.GetString("CurrentColor", resourceCulture);
            }
        }
        
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        public static string CyanInitial {
            get {
                return ResourceManager.GetString("CyanInitial", resourceCulture);
            }
        }
        
        public static string CyanMagentaYellowBlack {
            get {
                return ResourceManager.GetString("CyanMagentaYellowBlack", resourceCulture);
            }
        }
        
        public static string ConvertToLocalValue {
            get {
                return ResourceManager.GetString("ConvertToLocalValue", resourceCulture);
            }
        }
        
        public static string CustomExpressionEllipsis {
            get {
                return ResourceManager.GetString("CustomExpressionEllipsis", resourceCulture);
            }
        }
        
        public static string EventHandlersSelectedElement {
            get {
                return ResourceManager.GetString("EventHandlersSelectedElement", resourceCulture);
            }
        }
        
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        public static string GreenInitial {
            get {
                return ResourceManager.GetString("GreenInitial", resourceCulture);
            }
        }
        
        public static string HexValue {
            get {
                return ResourceManager.GetString("HexValue", resourceCulture);
            }
        }
        
        public static string HLS {
            get {
                return ResourceManager.GetString("HLS", resourceCulture);
            }
        }
        
        public static string HSB {
            get {
                return ResourceManager.GetString("HSB", resourceCulture);
            }
        }
        
        public static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        public static string HueInitial {
            get {
                return ResourceManager.GetString("HueInitial", resourceCulture);
            }
        }
        
        public static string HueLightnessSaturation {
            get {
                return ResourceManager.GetString("HueLightnessSaturation", resourceCulture);
            }
        }
        
        public static string HueSaturationBrightness {
            get {
                return ResourceManager.GetString("HueSaturationBrightness", resourceCulture);
            }
        }
        
        public static string InitialColor {
            get {
                return ResourceManager.GetString("InitialColor", resourceCulture);
            }
        }
        
        public static string LastColor {
            get {
                return ResourceManager.GetString("LastColor", resourceCulture);
            }
        }
        
        public static string Lightness {
            get {
                return ResourceManager.GetString("Lightness", resourceCulture);
            }
        }
        
        public static string LightnessInitial {
            get {
                return ResourceManager.GetString("LightnessInitial", resourceCulture);
            }
        }
        
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        public static string MagentaInitial {
            get {
                return ResourceManager.GetString("MagentaInitial", resourceCulture);
            }
        }
        
        public static string MultipleObjectsSelected {
            get {
                return ResourceManager.GetString("MultipleObjectsSelected", resourceCulture);
            }
        }
        
        public static string MultipleTypesSelected {
            get {
                return ResourceManager.GetString("MultipleTypesSelected", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        public static string PropertiesSelectedElement {
            get {
                return ResourceManager.GetString("PropertiesSelectedElement", resourceCulture);
            }
        }
        
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        public static string RedGreenBlue {
            get {
                return ResourceManager.GetString("RedGreenBlue", resourceCulture);
            }
        }
        
        public static string RedInitial {
            get {
                return ResourceManager.GetString("RedInitial", resourceCulture);
            }
        }
        
        public static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        public static string SaturationInitial {
            get {
                return ResourceManager.GetString("SaturationInitial", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string ViewPropertiesOrEvents {
            get {
                return ResourceManager.GetString("ViewPropertiesOrEvents", resourceCulture);
            }
        }
        
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        public static string YellowInitial {
            get {
                return ResourceManager.GetString("YellowInitial", resourceCulture);
            }
        }
        
        public static string NoBrush {
            get {
                return ResourceManager.GetString("NoBrush", resourceCulture);
            }
        }
        
        public static string SolidBrush {
            get {
                return ResourceManager.GetString("SolidBrush", resourceCulture);
            }
        }
        
        public static string ResourceBrush {
            get {
                return ResourceManager.GetString("ResourceBrush", resourceCulture);
            }
        }
        
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string ShowAllAssemblies {
            get {
                return ResourceManager.GetString("ShowAllAssemblies", resourceCulture);
            }
        }
        
        public static string SearchProperties {
            get {
                return ResourceManager.GetString("SearchProperties", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string SearchObjectsTitle {
            get {
                return ResourceManager.GetString("SearchObjectsTitle", resourceCulture);
            }
        }
        
        public static string SelectObjectTitle {
            get {
                return ResourceManager.GetString("SelectObjectTitle", resourceCulture);
            }
        }
        
        public static string CustomExpression {
            get {
                return ResourceManager.GetString("CustomExpression", resourceCulture);
            }
        }
        
        public static string ColorEditorTabLabel {
            get {
                return ResourceManager.GetString("ColorEditorTabLabel", resourceCulture);
            }
        }
        
        public static string SearchResourcesTitle {
            get {
                return ResourceManager.GetString("SearchResourcesTitle", resourceCulture);
            }
        }
        
        public static string SelectResourceTitle {
            get {
                return ResourceManager.GetString("SelectResourceTitle", resourceCulture);
            }
        }
        
        public static string ShowSystemResources {
            get {
                return ResourceManager.GetString("ShowSystemResources", resourceCulture);
            }
        }
        
        public static string ResourceEllipsis {
            get {
                return ResourceManager.GetString("ResourceEllipsis", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string Inherited {
            get {
                return ResourceManager.GetString("Inherited", resourceCulture);
            }
        }
        
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        public static string MaterialColorRed {
            get {
                return ResourceManager.GetString("MaterialColorRed", resourceCulture);
            }
        }
        
        public static string MaterialColorPink {
            get {
                return ResourceManager.GetString("MaterialColorPink", resourceCulture);
            }
        }
        
        public static string MaterialColorPurple {
            get {
                return ResourceManager.GetString("MaterialColorPurple", resourceCulture);
            }
        }
        
        public static string MaterialColorDeepPurple {
            get {
                return ResourceManager.GetString("MaterialColorDeepPurple", resourceCulture);
            }
        }
        
        public static string MaterialColorIndigo {
            get {
                return ResourceManager.GetString("MaterialColorIndigo", resourceCulture);
            }
        }
        
        public static string MaterialColorBlue {
            get {
                return ResourceManager.GetString("MaterialColorBlue", resourceCulture);
            }
        }
        
        public static string MaterialColorLightBlue {
            get {
                return ResourceManager.GetString("MaterialColorLightBlue", resourceCulture);
            }
        }
        
        public static string MaterialColorCyan {
            get {
                return ResourceManager.GetString("MaterialColorCyan", resourceCulture);
            }
        }
        
        public static string MaterialColorTeal {
            get {
                return ResourceManager.GetString("MaterialColorTeal", resourceCulture);
            }
        }
        
        public static string MaterialColorGreen {
            get {
                return ResourceManager.GetString("MaterialColorGreen", resourceCulture);
            }
        }
        
        public static string MaterialColorLightGreen {
            get {
                return ResourceManager.GetString("MaterialColorLightGreen", resourceCulture);
            }
        }
        
        public static string MaterialColorLime {
            get {
                return ResourceManager.GetString("MaterialColorLime", resourceCulture);
            }
        }
        
        public static string MaterialColorYellow {
            get {
                return ResourceManager.GetString("MaterialColorYellow", resourceCulture);
            }
        }
        
        public static string MaterialColorAmber {
            get {
                return ResourceManager.GetString("MaterialColorAmber", resourceCulture);
            }
        }
        
        public static string MaterialColorOrange {
            get {
                return ResourceManager.GetString("MaterialColorOrange", resourceCulture);
            }
        }
        
        public static string MaterialColorDeepOrange {
            get {
                return ResourceManager.GetString("MaterialColorDeepOrange", resourceCulture);
            }
        }
        
        public static string MaterialColorBrown {
            get {
                return ResourceManager.GetString("MaterialColorBrown", resourceCulture);
            }
        }
        
        public static string MaterialColorGrey {
            get {
                return ResourceManager.GetString("MaterialColorGrey", resourceCulture);
            }
        }
        
        public static string MaterialColorBlueGrey {
            get {
                return ResourceManager.GetString("MaterialColorBlueGrey", resourceCulture);
            }
        }
        
        public static string MaterialDesignColorBrush {
            get {
                return ResourceManager.GetString("MaterialDesignColorBrush", resourceCulture);
            }
        }
        
        public static string MaterialColorBlackAndWhite {
            get {
                return ResourceManager.GetString("MaterialColorBlackAndWhite", resourceCulture);
            }
        }
        
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        public static string NoPreviewAvailable {
            get {
                return ResourceManager.GetString("NoPreviewAvailable", resourceCulture);
            }
        }
        
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        public static string ResourceWithName {
            get {
                return ResourceManager.GetString("ResourceWithName", resourceCulture);
            }
        }
        
        public static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        public static string GoToSource {
            get {
                return ResourceManager.GetString("GoToSource", resourceCulture);
            }
        }
        
        public static string CollectionValue {
            get {
                return ResourceManager.GetString("CollectionValue", resourceCulture);
            }
        }
        
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        public static string OtherTypeAction {
            get {
                return ResourceManager.GetString("OtherTypeAction", resourceCulture);
            }
        }
        
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        public static string CollectionEditorTitle {
            get {
                return ResourceManager.GetString("CollectionEditorTitle", resourceCulture);
            }
        }
        
        public static string MoveItemDown {
            get {
                return ResourceManager.GetString("MoveItemDown", resourceCulture);
            }
        }
        
        public static string MoveItemUp {
            get {
                return ResourceManager.GetString("MoveItemUp", resourceCulture);
            }
        }
        
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        public static string DefineIn {
            get {
                return ResourceManager.GetString("DefineIn", resourceCulture);
            }
        }
        
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        public static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        public static string ThisDocument {
            get {
                return ResourceManager.GetString("ThisDocument", resourceCulture);
            }
        }
        
        public static string ConvertToNewResourceEllipsis {
            get {
                return ResourceManager.GetString("ConvertToNewResourceEllipsis", resourceCulture);
            }
        }
        
        public static string CreateResourceTitle {
            get {
                return ResourceManager.GetString("CreateResourceTitle", resourceCulture);
            }
        }
        
        public static string ResourceNameLabel {
            get {
                return ResourceManager.GetString("ResourceNameLabel", resourceCulture);
            }
        }
        
        public static string ResourceDictionary {
            get {
                return ResourceManager.GetString("ResourceDictionary", resourceCulture);
            }
        }
        
        public static string CreateDataBindingMenuItem {
            get {
                return ResourceManager.GetString("CreateDataBindingMenuItem", resourceCulture);
            }
        }
        
        public static string AddValueConverterEllipsis {
            get {
                return ResourceManager.GetString("AddValueConverterEllipsis", resourceCulture);
            }
        }
        
        public static string AddValueConverterTitle {
            get {
                return ResourceManager.GetString("AddValueConverterTitle", resourceCulture);
            }
        }
        
        public static string NoValueConverter {
            get {
                return ResourceManager.GetString("NoValueConverter", resourceCulture);
            }
        }
        
        public static string ValueConverterName {
            get {
                return ResourceManager.GetString("ValueConverterName", resourceCulture);
            }
        }
        
        public static string CreateDataBindingTitle {
            get {
                return ResourceManager.GetString("CreateDataBindingTitle", resourceCulture);
            }
        }
        
        public static string BindingType {
            get {
                return ResourceManager.GetString("BindingType", resourceCulture);
            }
        }
        
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        public static string ResourcePlural {
            get {
                return ResourceManager.GetString("ResourcePlural", resourceCulture);
            }
        }
        
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        public static string InvalidRatio {
            get {
                return ResourceManager.GetString("InvalidRatio", resourceCulture);
            }
        }
        
        public static string AllResources {
            get {
                return ResourceManager.GetString("AllResources", resourceCulture);
            }
        }
        
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        public static string AddVariationHelpText {
            get {
                return ResourceManager.GetString("AddVariationHelpText", resourceCulture);
            }
        }
        
        public static string AddVariationTitle {
            get {
                return ResourceManager.GetString("AddVariationTitle", resourceCulture);
            }
        }
        
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        public static string ErrorCreatingVariant {
            get {
                return ResourceManager.GetString("ErrorCreatingVariant", resourceCulture);
            }
        }
        
        public static string UncommonPropertiesTooltip {
            get {
                return ResourceManager.GetString("UncommonPropertiesTooltip", resourceCulture);
            }
        }
        
        public static string NewInstanceForProperty {
            get {
                return ResourceManager.GetString("NewInstanceForProperty", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string SelectTypeForProperty {
            get {
                return ResourceManager.GetString("SelectTypeForProperty", resourceCulture);
            }
        }
        
        public static string PropertyFilterLabel {
            get {
                return ResourceManager.GetString("PropertyFilterLabel", resourceCulture);
            }
        }
        
        public static string PropertyColumnTitle {
            get {
                return ResourceManager.GetString("PropertyColumnTitle", resourceCulture);
            }
        }
        
        public static string ValueColumnTitle {
            get {
                return ResourceManager.GetString("ValueColumnTitle", resourceCulture);
            }
        }
        
        public static string AccessibilityNumeric {
            get {
                return ResourceManager.GetString("AccessibilityNumeric", resourceCulture);
            }
        }
        
        public static string AccessibilityBoolean {
            get {
                return ResourceManager.GetString("AccessibilityBoolean", resourceCulture);
            }
        }
        
        public static string AccessibilityCombobox {
            get {
                return ResourceManager.GetString("AccessibilityCombobox", resourceCulture);
            }
        }
        
        public static string AccessibilityCollection {
            get {
                return ResourceManager.GetString("AccessibilityCollection", resourceCulture);
            }
        }
        
        public static string AccessibilityCollectionHelp {
            get {
                return ResourceManager.GetString("AccessibilityCollectionHelp", resourceCulture);
            }
        }
        
        public static string AccessibilityCollectionTypeSelector {
            get {
                return ResourceManager.GetString("AccessibilityCollectionTypeSelector", resourceCulture);
            }
        }
        
        public static string AccessibilityCollectionAddButton {
            get {
                return ResourceManager.GetString("AccessibilityCollectionAddButton", resourceCulture);
            }
        }
        
        public static string AccessibilityCollectionRemoveButton {
            get {
                return ResourceManager.GetString("AccessibilityCollectionRemoveButton", resourceCulture);
            }
        }
        
        public static string AccessibilityString {
            get {
                return ResourceManager.GetString("AccessibilityString", resourceCulture);
            }
        }
        
        public static string AccessibilityChar {
            get {
                return ResourceManager.GetString("AccessibilityChar", resourceCulture);
            }
        }
        
        public static string AccessibilityTimeSpan {
            get {
                return ResourceManager.GetString("AccessibilityTimeSpan", resourceCulture);
            }
        }
        
        public static string AccessibilityDateTime {
            get {
                return ResourceManager.GetString("AccessibilityDateTime", resourceCulture);
            }
        }
        
        public static string AccessibilityXEditor {
            get {
                return ResourceManager.GetString("AccessibilityXEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityYEditor {
            get {
                return ResourceManager.GetString("AccessibilityYEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityWidthEditor {
            get {
                return ResourceManager.GetString("AccessibilityWidthEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityHeightEditor {
            get {
                return ResourceManager.GetString("AccessibilityHeightEditor", resourceCulture);
            }
        }
        
        public static string ArrangeByLabel {
            get {
                return ResourceManager.GetString("ArrangeByLabel", resourceCulture);
            }
        }
        
        public static string AccessibilityPropertiesButton {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButton", resourceCulture);
            }
        }
        
        public static string AccessibilityPropertiesButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButtonDescription", resourceCulture);
            }
        }
        
        public static string AccessibilityActionButton {
            get {
                return ResourceManager.GetString("AccessibilityActionButton", resourceCulture);
            }
        }
        
        public static string AccessibilityActionButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityActionButtonDescription", resourceCulture);
            }
        }
        
        public static string CollectionTargetsHeader {
            get {
                return ResourceManager.GetString("CollectionTargetsHeader", resourceCulture);
            }
        }
        
        public static string CollectionEditButton {
            get {
                return ResourceManager.GetString("CollectionEditButton", resourceCulture);
            }
        }
        
        public static string ColumnResourceName {
            get {
                return ResourceManager.GetString("ColumnResourceName", resourceCulture);
            }
        }
        
        public static string ColumnResourcePreview {
            get {
                return ResourceManager.GetString("ColumnResourcePreview", resourceCulture);
            }
        }
        
        public static string ResourceTableImageColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableImageColumnTitle", resourceCulture);
            }
        }
        
        public static string ResourceTableTypeColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableTypeColumnTitle", resourceCulture);
            }
        }
        
        public static string ResourceTableNameColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableNameColumnTitle", resourceCulture);
            }
        }
        
        public static string ResourceTableValueColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableValueColumnTitle", resourceCulture);
            }
        }
        
        public static string CommonBrushTitleUnknown {
            get {
                return ResourceManager.GetString("CommonBrushTitleUnknown", resourceCulture);
            }
        }
        
        public static string CommonBrushTitleGradient {
            get {
                return ResourceManager.GetString("CommonBrushTitleGradient", resourceCulture);
            }
        }
        
        public static string AccessibilityObjectName {
            get {
                return ResourceManager.GetString("AccessibilityObjectName", resourceCulture);
            }
        }
        
        public static string ObjectNamePlaceholder {
            get {
                return ResourceManager.GetString("ObjectNamePlaceholder", resourceCulture);
            }
        }
        
        public static string AccessibilityLeftEditor {
            get {
                return ResourceManager.GetString("AccessibilityLeftEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityTopEditor {
            get {
                return ResourceManager.GetString("AccessibilityTopEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityRightEditor {
            get {
                return ResourceManager.GetString("AccessibilityRightEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityBottomEditor {
            get {
                return ResourceManager.GetString("AccessibilityBottomEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityInputModeEditor {
            get {
                return ResourceManager.GetString("AccessibilityInputModeEditor", resourceCulture);
            }
        }
        
        public static string AccessibilityPathEditor {
            get {
                return ResourceManager.GetString("AccessibilityPathEditor", resourceCulture);
            }
        }
        
        public static string ChooseFileOrDirectory {
            get {
                return ResourceManager.GetString("ChooseFileOrDirectory", resourceCulture);
            }
        }
        
        public static string BrowseFileOrDirectory {
            get {
                return ResourceManager.GetString("BrowseFileOrDirectory", resourceCulture);
            }
        }
        
        public static string RevealFileOrDirectory {
            get {
                return ResourceManager.GetString("RevealFileOrDirectory", resourceCulture);
            }
        }
        
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        public static string AddVariant {
            get {
                return ResourceManager.GetString("AddVariant", resourceCulture);
            }
        }
        
        public static string RemoveVariant {
            get {
                return ResourceManager.GetString("RemoveVariant", resourceCulture);
            }
        }
        
        public static string CreateBindingTitle {
            get {
                return ResourceManager.GetString("CreateBindingTitle", resourceCulture);
            }
        }
        
        public static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        public static string HideSettings {
            get {
                return ResourceManager.GetString("HideSettings", resourceCulture);
            }
        }
        
        public static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        public static string SelectTypeTitle {
            get {
                return ResourceManager.GetString("SelectTypeTitle", resourceCulture);
            }
        }
        
        public static string DoneTitle {
            get {
                return ResourceManager.GetString("DoneTitle", resourceCulture);
            }
        }
    }
}
