//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.PropertyEditing.Mac.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.PropertyEditing.Mac.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PropertyFilterLabel {
            get {
                return ResourceManager.GetString("PropertyFilterLabel", resourceCulture);
            }
        }
        
        internal static string PropertyColumnTitle {
            get {
                return ResourceManager.GetString("PropertyColumnTitle", resourceCulture);
            }
        }
        
        internal static string ValueColumnTitle {
            get {
                return ResourceManager.GetString("ValueColumnTitle", resourceCulture);
            }
        }
        
        internal static string AccessibilityNumeric {
            get {
                return ResourceManager.GetString("AccessibilityNumeric", resourceCulture);
            }
        }
        
        internal static string AccessibilityBoolean {
            get {
                return ResourceManager.GetString("AccessibilityBoolean", resourceCulture);
            }
        }
        
        internal static string AccessibilityCombobox {
            get {
                return ResourceManager.GetString("AccessibilityCombobox", resourceCulture);
            }
        }
        
        internal static string AccessibilityChar {
            get {
                return ResourceManager.GetString("AccessibilityChar", resourceCulture);
            }
        }
        
        internal static string AccessibilityString {
            get {
                return ResourceManager.GetString("AccessibilityString", resourceCulture);
            }
        }
        
        internal static string AccessibilityXEditor {
            get {
                return ResourceManager.GetString("AccessibilityXEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityYEditor {
            get {
                return ResourceManager.GetString("AccessibilityYEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityWidthEditor {
            get {
                return ResourceManager.GetString("AccessibilityWidthEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityHeightEditor {
            get {
                return ResourceManager.GetString("AccessibilityHeightEditor", resourceCulture);
            }
        }
        
        internal static string ArrangeByLabel {
            get {
                return ResourceManager.GetString("ArrangeByLabel", resourceCulture);
            }
        }
        
        internal static string AccessibilityPropertiesButton {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButton", resourceCulture);
            }
        }
        
        internal static string AccessibilityPropertiesButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButtonDescription", resourceCulture);
            }
        }
        
        internal static string AccessibilityActionButton {
            get {
                return ResourceManager.GetString("AccessibilityActionButton", resourceCulture);
            }
        }
        
        internal static string AccessibilityActionButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityActionButtonDescription", resourceCulture);
            }
        }
        
        internal static string ColumnResourceName {
            get {
                return ResourceManager.GetString("ColumnResourceName", resourceCulture);
            }
        }
        
        internal static string ColumnResourcePreview {
            get {
                return ResourceManager.GetString("ColumnResourcePreview", resourceCulture);
            }
        }
        
        internal static string ResourceTableImageColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableImageColumnTitle", resourceCulture);
            }
        }
        
        internal static string ResourceTableTypeColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableTypeColumnTitle", resourceCulture);
            }
        }
        
        internal static string ResourceTableNameColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableNameColumnTitle", resourceCulture);
            }
        }
        
        internal static string ResourceTableValueColumnTitle {
            get {
                return ResourceManager.GetString("ResourceTableValueColumnTitle", resourceCulture);
            }
        }
        
        internal static string CommonBrushTitleUnknown {
            get {
                return ResourceManager.GetString("CommonBrushTitleUnknown", resourceCulture);
            }
        }
        
        internal static string CommonBrushTitleGradient {
            get {
                return ResourceManager.GetString("CommonBrushTitleGradient", resourceCulture);
            }
        }
        
        internal static string AccessibilityObjectName {
            get {
                return ResourceManager.GetString("AccessibilityObjectName", resourceCulture);
            }
        }
        
        internal static string ObjectNamePlaceholder {
            get {
                return ResourceManager.GetString("ObjectNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string AccessibilityLeftEditor {
            get {
                return ResourceManager.GetString("AccessibilityLeftEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityTopEditor {
            get {
                return ResourceManager.GetString("AccessibilityTopEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityRightEditor {
            get {
                return ResourceManager.GetString("AccessibilityRightEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityBottomEditor {
            get {
                return ResourceManager.GetString("AccessibilityBottomEditor", resourceCulture);
            }
        }
        
        internal static string AccessibilityInpueModeEditor {
            get {
                return ResourceManager.GetString("AccessibilityInpueModeEditor", resourceCulture);
            }
        }
    }
}
