//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.PropertyEditing.Mac.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.PropertyEditing.Mac.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Boolean Editor.
        /// </summary>
        internal static string AccessibilityBoolean {
            get {
                return ResourceManager.GetString("AccessibilityBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Combobox Editor.
        /// </summary>
        internal static string AccessibilityCombobox {
            get {
                return ResourceManager.GetString("AccessibilityCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Height Editor.
        /// </summary>
        internal static string AccessibilityHeightEditor {
            get {
                return ResourceManager.GetString("AccessibilityHeightEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Numeric Editor.
        /// </summary>
        internal static string AccessibilityNumeric {
            get {
                return ResourceManager.GetString("AccessibilityNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} String Editor.
        /// </summary>
        internal static string AccessibilityString {
            get {
                return ResourceManager.GetString("AccessibilityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Width Editor.
        /// </summary>
        internal static string AccessibilityWidthEditor {
            get {
                return ResourceManager.GetString("AccessibilityWidthEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} X Editor.
        /// </summary>
        internal static string AccessibilityXEditor {
            get {
                return ResourceManager.GetString("AccessibilityXEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Y Editor.
        /// </summary>
        internal static string AccessibilityYEditor {
            get {
                return ResourceManager.GetString("AccessibilityYEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange By:.
        /// </summary>
        internal static string ArrangeByLabel {
            get {
                return ResourceManager.GetString("ArrangeByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PropertyColumnTitle {
            get {
                return ResourceManager.GetString("PropertyColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Filter.
        /// </summary>
        internal static string PropertyFilterLabel {
            get {
                return ResourceManager.GetString("PropertyFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueColumnTitle {
            get {
                return ResourceManager.GetString("ValueColumnTitle", resourceCulture);
            }
        }
        
        internal static string AccessibilityPropertiesButton {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButton", resourceCulture);
            }
        }
        
        internal static string AccessibilityPropertiesButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityPropertiesButtonDescription", resourceCulture);
            }
        }
        
        internal static string AccessibilityActionButton {
            get {
                return ResourceManager.GetString("AccessibilityActionButton", resourceCulture);
            }
        }
        
        internal static string AccessibilityActionButtonDescription {
            get {
                return ResourceManager.GetString("AccessibilityActionButtonDescription", resourceCulture);
            }
        }
    }
}
