stages:
  - template: security/full/v0.yml@templates
    parameters:
      windowsPoolName: 'windows-2022'
      windowsImageOverride: 'windows-2022'
      complianceEnabled: true
      scanArtifacts: ['Symbols']
      antiMalwareEnabled: true
      binSkimEnabled: true
      credScanEnabled: true
      credScanSuppressionFile: '$(System.DefaultWorkingDirectory)\.config\CredScanSuppressions.json'
      tsaConfigFile: '$(System.DefaultWorkingDirectory)\.build\automation\tsaoptions-v2.json'
      policheckLocScanEnabled: true
      policheckExclusionFilesFolder: '$(System.DefaultWorkingDirectory)\.config\Policheck'
      policheckSrcScanFolder: '$(System.DefaultWorkingDirectory)'
