stages:
  - template: security/full/v0.yml@templates
    parameters:
      windowsPoolName: 'Hosted Windows 2019 with VS2019'
      complianceEnabled: true
      antiMalwareEnabled: true
      binSkimEnabled: true
      credScanEnabled: true
      credScanSuppressionFile: '$(System.DefaultWorkingDirectory)\.config\CredScanSuppressions.json'
      tsaConfigFile: '$(System.DefaultWorkingDirectory)\.build\automation\tsaoptions-v2.json'
      policheckLocScanEnabled: false

  # For now, continue to run policheck as we did before, not running it from the template
  - stage: policheck
    displayName: Policheck
    jobs:
    # Check - "Code Analysis Policheck Compliance"
    # For a full list of termType and the correct code refer to https://github.com/xamarin/yaml-templates/blob/master/security/policheck/v1.yml
    - job: run_policheck_compliance
      displayName: 'Policheck Compliance Source'
      pool: $(HostedWinVS2019)
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5
      strategy:
        matrix:
          SourceCodeOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.xml'
            TERM_TYPE: '0029a9'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          CzechResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.cs.xml'
            TERM_TYPE: '0025a1029'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          GermanResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.de.xml'
            TERM_TYPE: '0036a1031'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          EnglishResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.en.xml'
            TERM_TYPE: '0029a9'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          SpanishResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.es.xml'
            TERM_TYPE: '0099a1034'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          FrenchResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.fr.xml'
            TERM_TYPE: '0033a1036'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          ItalianResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.it.xml'
            TERM_TYPE: '0051a1040'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          JapaneseResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.ja.xml'
            TERM_TYPE: '0052a1041'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          KoreanResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.ko.xml'
            TERM_TYPE: '0060a1042'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          PolishResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.pl.xml'
            TERM_TYPE: '0079a1045'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          PortugeseBrazilianResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.pt-br.xml'
            TERM_TYPE: '0080a1046'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          RussianResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.ru.xml'
            TERM_TYPE: '0087a1049'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          TurkeyResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.tr.xml'
            TERM_TYPE: '0107a1055'
            OPTIONS_PE: ''
            OPTIONS_RULES_DB_PATH: ''
          ChineseSimplifiedResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.zh-hans.xml'
            TERM_TYPE: '0021a2052'
            OPTIONS_PE: '1|2|3|4'
            OPTIONS_RULES_DB_PATH: '$(System.DefaultWorkingDirectory)\.config\Policheck\Rule-zh-all.mdb'
          ChineseTraditionalResourceOnly:
            EXCLUSION_FILE: '$(System.DefaultWorkingDirectory)\.config\Policheck\UserExclusion.zh-hant.xml'
            TERM_TYPE: '0022a3076'
            OPTIONS_PE: '1|2|3|4'
            OPTIONS_RULES_DB_PATH: '$(System.DefaultWorkingDirectory)\.config\Policheck\Rule-zh-all.mdb'
      steps:
      - checkout: self
      - template: security/policheck/v1.yml@templates
        parameters:
          exclusionFile: $(EXCLUSION_FILE)
          termType: $(TERM_TYPE)
          pE: $(OPTIONS_PE)
          rulesDBPath: $(OPTIONS_RULES_DB_PATH)

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
        displayName: 'Post Analysis'
        inputs:
          AllTools: true
    