stages:
  - stage: merge_translations_updates
    displayName: 'Merge Translations Updates'
    dependsOn: [Build]
    condition: and( succeeded(), and( eq(variables.isTargetMainBranch, true), variables.isLocPRBranch ) ) 

    jobs:
      - job : validate_merge
        displayName: 'Validate and Merge Translations'
        pool:
          name: $(HostedWinVS2019)
        variables:
          pull_request_number: $(System.PullRequest.PullRequestNumber)
        workspace:
          clean: all

        steps:
          - powershell: |
              Write-Host "Validating translations for PR# $(System.PullRequest.PullRequestNumber)"
              $srcDir = "$(Build.SourcesDirectory)/Xamarin.PropertyEditing"
              $matches = Select-String -Path "$srcDir/**/*.resx" -Pattern '\[.*\]\s\(https:.*\)' -AllMatches
              $matchCount = ($matches | Measure-Object -Line).Lines
              Write-Host "Found $matchCount violations."
              $matches | Write-Host
              if( ($matches | Measure-Object -Line).Lines -eq 0 ) {
                Write-Host "Quality Gate Succeeded."
              } else {
                throw "Quality Gate Failure : Check the logs for details."
              }
            displayName: 'Validate Markdown Urls'

          - task: github-merge-pr@1
            inputs:
              github_token: $(GitHub.Token)
              repository: 'xamarin/uitools'
              pr_number: $(pull_request_number)
              merge_method: 'rebase'
            displayName: Merge PR# $(System.PullRequest.PullRequestNumber)
