stages:
  - template: foobar
    parameters:
      complianceEnabled: true
      scanArtifacts: ['Symbols']
      antiMalwareEnabled: true
      binSkimEnabled: true
      credScanEnabled: true
      credScanSuppressionFile: '$(System.DefaultWorkingDirectory)\.config\CredScanSuppressions.json'
      tsaConfigFile: '$(System.DefaultWorkingDirectory)\.build\automation\tsaoptions-v2.json'
      policheckLocScanEnabled: true
      policheckExclusionFilesFolder: '$(System.DefaultWorkingDirectory)\.config\Policheck'
      policheckSrcScanFolder: '$(System.DefaultWorkingDirectory)'
