name: Localization-CI

on:
  push:
    branches: 
      - loc

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create PR
      uses: funivan/github-autopr@0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: .ref refs/heads/loc -vv
