name: Rebase Trigger

on:
  issue_comment:
    types: [created]

jobs:
  launchBackportBuild:
    runs-on: ubuntu-latest
    # GITHUB_TOKEN change from read-write to read-only on 2024-02-01 requires permissions block
    # https://docs.opensource.microsoft.com/github/apps/permission-changes/
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      actions: write
      contents: read
      security-events: write
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@gitbot rebase')

    steps:
      - uses: xamarin/rebase-bot-action@v1.0
        with:
          pull_request_url: ${{ github.event.issue.pull_request.url }}
          comment_author: ${{ github.actor }}
          github_repository: ${{ github.repository }}
          ado_organization: ${{ secrets.ADO_PROJECTCOLLECTION }}
          ado_project: ${{ secrets.ADO_PROJECT }}
          rebase_pipeline_id: 13926
          ado_build_pat: ${{ secrets.ADO_BUILDPAT }}
          github_account_pat: ${{ secrets.SERVICEACCOUNT_PAT }}
